# Switch Class Driver

obj-$(CONFIG_BBK_FP_ID)	+= fp_id.o
obj-$(CONFIG_BBK_GOODIX3208)   += gf3208/
obj-$(CONFIG_BBK_GOODIX5288)   += gf5288/
obj-$(CONFIG_BBK_FS9501) 	+= fs9501/
obj-$(CONFIG_BBK_GOODIX9118)   += gf9118/
obj-$(CONFIG_BBK_GOODIX9518)   += gf9518/