obj-$(CONFIG_VIVO_REGDUMP) += vivo-regdump.o
obj-$(CONFIG_SND_HIFI_CODEC_COMMON) += vivo-codec-common.o

#obj-$(CONFIG_SND_AK4376) +=ak4376.o
obj-y += vivo-regdump.o
obj-y += vivo-codec-common.o
obj-y += ak4376.o
#obj-y += vivo-codec-default.o

#obj-$(CONFIG_SND_ES9118) += es9118.o
obj-y += es9118.o

#obj-$(CONFIG_SND_TFA98XX) += snd-soc-tfa98xx.o
obj-y += snd-soc-tfa98xx.o
snd-soc-tfa98xx-objs += tfa98xx.o
snd-soc-tfa98xx-objs += tfa_container.o
snd-soc-tfa98xx-objs += tfa_dsp.o
snd-soc-tfa98xx-objs += tfa9888_init.o
snd-soc-tfa98xx-objs += tfa9891_init.o
snd-soc-tfa98xx-objs += tfa9897_init.o
snd-soc-tfa98xx-objs += tfa9890_init.o
snd-soc-tfa98xx-objs += tfa9887B_init.o
snd-soc-tfa98xx-objs += tfa9887_init.o
snd-soc-tfa98xx-objs += tfa98xx-debug-common.o

obj-y += tfa9894/

#obj-$(CONFIG_SND_SOC_MAX98927) += snd-soc-max98927.o
obj-y += snd-soc-max98927.o
snd-soc-max98927-objs += max98927.o
snd-soc-max98927-objs += max989xx-debug-common.o

#obj-$(CONFIG_SND_HIFI_CODEC_TD1608) += vivo-codec-td1608.o
obj-y += vivo-codec-td1608.o

obj-y += vivo-audio-test.o
